# Generated by Django 2.1.5 on 2019-02-15 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baptism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField()),
                ('registry_number', models.CharField(max_length=64)),
                ('record_number', models.CharField(max_length=64)),
                ('page_number', models.CharField(max_length=64)),
                ('remarks', models.CharField(max_length=1024)),
                ('date', models.DateTimeField()),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('legitimacy', models.SmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField()),
                ('or_number', models.CharField(max_length=255)),
                ('received_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=16)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='sacrament.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('suggested_price', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField()),
                ('registry_number', models.CharField(max_length=64)),
                ('record_number', models.CharField(max_length=64)),
                ('page_number', models.CharField(max_length=64)),
                ('remarks', models.CharField(max_length=1024)),
                ('date', models.DateTimeField()),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Minister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('suffix', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('ministry_type', models.SmallIntegerField()),
                ('status', models.SmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('suffix', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('gender', models.BooleanField()),
                ('birthplace', models.CharField(max_length=255)),
                ('residence', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('suffix', models.CharField(max_length=255)),
                ('residence', models.CharField(max_length=511)),
                ('baptism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sponsors', to='sacrament.Baptism')),
                ('confirmation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sponsors', to='sacrament.Confirmation')),
                ('marriage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sponsors', to='sacrament.Marriage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='marriage',
            name='bride_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brides', to='sacrament.Profile'),
        ),
        migrations.AddField(
            model_name='marriage',
            name='groom_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grooms', to='sacrament.Profile'),
        ),
        migrations.AddField(
            model_name='marriage',
            name='minister',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marriages', to='sacrament.Minister'),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='minister',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmations', to='sacrament.Minister'),
        ),
        migrations.AddField(
            model_name='baptism',
            name='minister',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baptisms', to='sacrament.Minister'),
        ),
        migrations.AddField(
            model_name='baptism',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baptism', to='sacrament.Profile'),
        ),
    ]
