# Generated by Django 2.1.5 on 2019-03-18 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baptism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Approved'), (1, 'Declined'), (2, 'Pending'), (3, 'Finished')])),
                ('registry_number', models.CharField(blank=True, max_length=64, null=True)),
                ('record_number', models.CharField(blank=True, max_length=64, null=True)),
                ('page_number', models.CharField(blank=True, max_length=64, null=True)),
                ('remarks', models.CharField(blank=True, max_length=1024, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('legitimacy', models.SmallIntegerField(choices=[(0, 'Natural'), (1, 'Civil'), (2, 'Legal')], max_length=1)),
                ('mother_first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('mother_middle_name', models.CharField(blank=True, max_length=64, null=True)),
                ('mother_last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('father_first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('father_middle_name', models.CharField(blank=True, max_length=64, null=True)),
                ('father_last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('mother_suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('father_suffix', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Approved'), (1, 'Declined'), (2, 'Pending'), (3, 'Finished')])),
                ('registry_number', models.CharField(blank=True, max_length=64, null=True)),
                ('record_number', models.CharField(blank=True, max_length=64, null=True)),
                ('page_number', models.CharField(blank=True, max_length=64, null=True)),
                ('remarks', models.CharField(blank=True, max_length=1024, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Approved'), (1, 'Declined'), (2, 'Pending'), (3, 'Finished')])),
                ('registry_number', models.CharField(blank=True, max_length=64, null=True)),
                ('record_number', models.CharField(blank=True, max_length=64, null=True)),
                ('page_number', models.CharField(blank=True, max_length=64, null=True)),
                ('remarks', models.CharField(blank=True, max_length=1024, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Minister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('suffix', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.DateField()),
                ('ministry_type', models.SmallIntegerField(choices=[(0, 'Cardinal'), (1, 'Archbishop'), (2, 'Bishop'), (3, 'Priest')], max_length=1)),
                ('status', models.SmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('suffix', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.DateField()),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('birthplace', models.CharField(blank=True, max_length=255, null=True)),
                ('residence', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('suffix', models.CharField(blank=True, max_length=255, null=True)),
                ('residence', models.CharField(max_length=511)),
                ('baptism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sponsors', to='sacrament.Baptism')),
                ('confirmation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sponsors', to='sacrament.Confirmation')),
                ('marriage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sponsors', to='sacrament.Marriage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='marriage',
            name='bride_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brides', to='sacrament.Profile'),
        ),
        migrations.AddField(
            model_name='marriage',
            name='groom_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grooms', to='sacrament.Profile'),
        ),
        migrations.AddField(
            model_name='marriage',
            name='minister',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marriages', to='sacrament.Minister'),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='minister',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmations', to='sacrament.Minister'),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmation', to='sacrament.Profile'),
        ),
        migrations.AddField(
            model_name='baptism',
            name='minister',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baptisms', to='sacrament.Minister'),
        ),
        migrations.AddField(
            model_name='baptism',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baptism', to='sacrament.Profile'),
        ),
    ]
