# Generated by Django 2.1.5 on 2019-02-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'treasurer'), (2, 'secretary'), (3, 'supervisor'), (4, 'admin')], null=True),
        ),
    ]
